#!/bin/sh

#colors
c1="\033[1;30m"
c2="\033[1;31m"
c3="\033[1;32m"
c4="\033[1;33m"
c5="\033[1;34m"
c6="\033[1;35m"
c7="\033[1;36m"
c8="\033[1;37m"
end="\033[1;0m"
colors=( "$c1" "$c2" "$c1" "$c3" "$c1" "$c4" "$c1" "$c6" "$c1" "$c7" "$c1" "$c8" "$c1" )
seed=${#colors[@]}

text="$1"
wait="$2"

while true; do
  color=$(($RANDOM%${seed}))
  printf "${colors[$color]}" 
  printf "$text"
  sleep $wait &> /dev/null
done
printf " \n"
