#!/bin/sh

host="$(cat /proc/sys/kernel/hostname)"
user=$(sh -c 'whoami')
os=$(. /etc/os-release && echo $ID)
read -r _ _ version _ < /proc/version
kr=${version%%-*}
sh=${SHELL##*/}
wm="sway"

YELLOW='\033[1;33m'
CYAN='\033[1;34m'
NC='\033[0m'

printf "
  ${YELLOW}${user}${NC}@${YELLOW}${host}${NC}
  ${CYAN}os${NC}  ->  ${os}
  ${CYAN}kr${NC}  ->  ${kr}
  ${CYAN}sh${NC}  ->  ${sh}
  ${CYAN}wm${NC}  ->  ${wm}

" | tr '[:upper:]' '[:lower:]'
