#!/bin/sh
read -r host < /proc/sys/kernel/hostname
read -r kernel < /proc/sys/kernel/osrelease
. /etc/os-release

## rose
read -r -d '' rose <<- EOM
\\033c\\033[31m    .--.---.
   ( \\'--'/ )
  ( '..-...' )
   '.'-._.'.'
 \\033[34m   <'-.,.->
       \`\\(   _
       < \\ / \\
       __ \\\\|_/
      /  \\ \\\\
       '--'.\\ >
             \\\\\\033[0m
EOM

## user
user=${USER:-$(id -un)}

## host
host=${HOSTNAME:-${host:-$(hostname)}}
[ "$host" ] || read -r host < /etc/hostname

## wm
[ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
  id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
  id=${id##* }
  wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
    grep '^_NET_WM_NAME' | cut -d\" -f 2)
}

## kernel
ke=$(uname -r)

## Packages
if command -v pacman >/dev/null; then
	pa=$(pacman -Q | wc -l)
elif command -v rpm >/dev/null; then
	pa=$(rpm -qa | wc -l)
elif command -v nix-env >/dev/null; then
	pa=$(nix-store -q --requisites ~/.nix-profile | wc -l)
elif command -v dpkg >/dev/null; then
	pkgs="$(grep -G '^Package:' -c /var/lib/dpkg/status)"
	pkgs=$(( pkgs - 32 ))
fi

## mem
mem() {
	free --mega | sed -n -E '2s/^[^0-9]*([0-9]+) *([0-9]+).*/'"${space}"'\2 \/ \1 MB/p'
}

## palette
s='[7m';   e='[m'
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[30m'; c8='[37m'
palette="$s$c7 $c7 $c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 $c8 $c8 $e"

## output
printf "%b\\n\\n" "$rose"
printf '%s\n' "
${c3}${user}${c8}@${c3}${host}${c8}
${c6}os${c8} >>= ${PRETTY_NAME}
${c6}sh${c8} >>= ${SHELL##*/}
${c6}pa${c8} >>= ${pa}
${c6}wm${c8} >>= ${wm}
${c6}kr${c8} >>= ${ke}
${c6}me${c8} >>= $(mem)

  ${palette}
"
