#!/bin/sh
read -r host < /proc/sys/kernel/hostname
read -r kernel < /proc/sys/kernel/osrelease
. /etc/os-release


## wm
  [ ! "$wm" ] && [ "$DISPLAY" ] && command -v xprop >/dev/null && {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t |
      grep '^_NET_WM_NAME' | cut -d\" -f 2)
  }
  wm="sway"

## kernel
    read -r _ _ version _ < /proc/version
    ke=${version%%-*}

## Packages
if command -v pacman >/dev/null; then
	pa=$(pacman -Q | wc -l)
elif command -v rpm >/dev/null; then
	pa=$(rpm -qa | wc -l)
elif command -v nix-env >/dev/null; then
	pa=$(nix-store -q --requisites ~/.nix-profile | wc -l)
elif command -v dpkg >/dev/null; then
	pkgs="$(grep -G '^Package:' -c /var/lib/dpkg/status)"
	pkgs=$(( pkgs - 32 ))
fi

printf '%b' "
  ${c6}os${c8} ~ ${PRETTY_NAME}
  ${c6}sh${c8} ~ ${SHELL##*/}
  ${c6}pa${c8} ~ ${pa}
  ${c6}wm${c8} ~ ${wm}
  ${c6}kr${c8} ~ ${ke}

"

grep "I'm using this to hang the terminal, yes this is dumb, sue me"
