(in-package #:nyxt-user)

;; this uses a theme from the autogenereated `base16.lisp` file generated by nix
;; if you are borrowing this code, make sure to write the file yourself

;; increase size of message-buffer
(define-configuration (window)
  ((message-buffer-height 21)))

;; quick function to easily make things important
(defun make-important (property)
  (str:concat property " !important"))

;; message buffer appearence
(define-configuration (window)
 ((message-buffer-style
  (theme:themed-css (theme *browser*)
    `(*
      :font-family ,*font*)
    `(body
      :background-color ,*base00*
      :color ,*base05*
      :opacity 1
      :font-size "11px"
      :padding 0
      :padding-left "9px"
      :margin "3px")))))

;; prompt buffer appearence
(define-configuration prompt-buffer
  ((style (str:concat
            %slot-value%
            (theme:themed-css (theme *browser*)  
              `(*
                :font-family ,*font*
                :font-size "11px")
              `("#prompt-area"
                :display "grid"
                :grid-template-columns "auto auto 1fr auto")
              `("#prompt, #prompt-extra, #prompt-area"
                :font-size "13px"
                :background-color ,*base01*
                :color ,*base06*
                :line-height "unset"
                :padding "5px"
                :padding-left "9px")
              `("#input"
                :background-color ,*base00*
                :color ,*base05*)
              `(button
                :all "unset"
                :background-color ,*base00*
                :font-size "13px"
                :margin "2px 12px 2px 0px"
                :padding "3px 6px")
              `("button[title=vi-normal-mode], button[title=vi-insert-mode]:hover"
                :color ,*base0F*)
              `("button[title=vi-insert-mode], button[title=vi-normal-mode]:hover"
                :color ,*base0C*)
              `(".source"
                :margin "0px")
              `(".source-name"
                :color ,*base05*)
              `(".source-content th"
                :background-color ,*base01*
                :border-color ,*base01*
                :color ,*base05*)
              `("#selection"
                :color ,*base00*)
              `(".marked"
                :background-color ,*base02*
                :color ,*base02*))))))

;; web buffer appearence
(define-configuration web-buffer
  ((style (str:concat
            %slot-value%
            (theme:themed-css (theme *browser*)
              `("a:hover"
                :color ,*base04*)
              `("a:active"
                :color ,*base06*)
              `(".button"
                :background-color ,(make-important *base00*)
                :background-color ,*base00*
                :border-color ,*base00*
                :color ,*base04*)
              `(".button:hover"
                :background-color ,(make-important *base01*)
                :color ,*base04*
                :border-color ,(make-important *base01*)
                :opacity 1)
              `(".button:active"
                :background-color ,(make-important *base01*)
                :border-color ,(make-important *base01*)
                :color ,*base04*)
              `(".button:visited"
                :color ,*base0C*)
              `(".button:visited:active"
                :color ,*base00*)
              `("h2, h3, h4, h5, h6"
                :color ,(make-important *base05*))
              `("#subtitle"
                :color ,(make-important *base0C*)))))))

;; repl buffer appearence
(define-configuration nyxt/repl-mode:repl-mode
  ((style (str:concat
            %slot-value%
            (theme:themed-css (theme *browser*)
              `(".input"
                :background-color ,*base01*
                :border-color ,*base01*
                :color ,*base05*)
              `(".input-buffer"
                :background-color ,*base00*
                :color ,*base04*
                :opacity 1)
              `(".button"
                :background-color ,*base00*
                :background-color ,*base00*
                :border-color ,*base00*
                :color ,*base04*)
              `(".button:hover"
                :background-color ,*base01*
                :color ,*base04*
                :border-color ,*base01*
                :opacity 1)
              `(".button:active"
                :background-color ,*base01*
                :border-color ,*base01*
                :color ,*base04*)
              `(".input-buffer::placeholder"
                :color ,*base0C*))))))

;; small web appearence
(define-configuration nyxt/small-web-mode:small-web-mode
  ((style (str:concat
            %slot-value%
            (theme:themed-css (theme *browser*)
              `("pre"
                :background-color ,*base00*)
              `("a.button.search"
                :color ,*base04*
                :border-color ,*base04*)
              `("a.button.error"
                :color ,*base0C*
                :border-color ,*base0C*))))))
