* Dotfiles
Managed via [[https://github.com/LnL7/nix-darwin][Nix-Darwin]], and [[https://github.com/nix-community/home-manager][Home-Manager]]

** Installation
*Warning:* If you want to give these dotfiles a try, you should first
fork this repository, review the code, and remove things you don't want
or need. Don't blindly use my settings unless you know what that
entails.

Currently this only works on aarch64-darwin systems. It will likely work on x86_64-darwin systems with minimal modifications, but I haven't tested it.

** Install
Install nix:
#+begin_src sh
sh <(curl -L https://nixos.org/nix/install) --daemon
#+end_src

Launch an ephemeral shell with git and nix unstable
#+begin_src sh
nix-shell -p nixUnstable git
#+end_src

Clone, build, and switch to the dotfiles
#+begin_src sh
git clone --depth 1 https://github.com/shaunsingh/nix-darwin-dotfiles.git ~/nix-darwin-dotfiles/ && cd nix-darwin-dotfiles
nix build ~/nix-darwin-dotfiles\#darwinConfigurations.shaunsingh-laptop.system --extra-experimental-features nix-command --extra-experimental-features flakes
./result/sw/bin/darwin-rebuild switch --flake .#shaunsingh-laptop
#+end_src

Symlinking with nix (and =nix-doom-emacs=) is very finicky, so for now use the following:
#+begin_src sh
ln -s ~/nix-darwin-dotfiles/configs/doom/ ~/.config/doom
ln -s ~/nix-darwin-dotfiles/configs/nvim/ ~/.config/nvim
#+end_src

You may also need to install doom emacs (and tangle the files)
#+begin_src sh
emacs --batch --eval "(progn (require 'org) (setq org-confirm-babel-evaluate nil) (org-babel-tangle-file \"~/nix-darwin-dotfiles/configs/doom/config.org\"))"
git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.config/emacs
~/.config/emacs/bin/doom install
#+end_src

*** Emacs
If you want to use [[https://github.com/emacs-ng/emacs-ng][Emacs-NG]], use the following build options
#+begin_src sh
  git clone --depth 1 https://github.com/emacs-ng/emacs-ng.git
  cd emacs-ng
  ./autogen.sh
  ./configure CFLAGS="-Wl,-rpath,shared,--disable-new-dtags -g -O3 -mtune=native -march=native -fomit-frame-pointer" \
              --prefix=/usr/local/ \
              --with-json --with-modules --with-compress-install \
              --with-threads --with-included-regex --with-zlib --with-libsystemd \
              --with-rsvg --with-native-compilation --with-webrender --without-javascript \
              --without-sound --without-imagemagick --without-makeinfo --without-gpm --without-dbus \
              --without-pop --without-toolkit-scroll-bars --without-mailutils --without-gsettings \
              --with-all
  make -j$(($(nproc) * 2)) NATIVE_FULL_AOT=1
  make install-strip
#+end_src

If you want to force recompile the literate configuration, you can run
#+begin_src sh
doom sync -u
#+end_src

If you want to update the doom configuration, you can run
#+begin_src sh
doom upgrade
#+end_src

If you modify your shell configuration, run =doom env= to regenerate env vars

**** Mu4e and Gmail
Email will have a few issues, since its hardcoded to my account. Replace instances of my name and email in =~/.doom.d/config.org=

Indexed mail will go under =~/.mbsync/=, you can either manually run mbsync
or use emacs to update mail.

**** Org Mode
My org mode config includes two additional plugins, org-agenda and
org-roam. Both these plugins need a set directory. All org files can go
under the created =~/org= dir. Roam files go under =~/org/roam=

** Additional Configurations
*** Fonts
 [[https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized][SFMono]] must be installed seperately, currently both Overpass and Alegreya are
 managed via nix.

*** Neovim
Run =:PackerSync= to install packer and plugins. Run =:checkhealth= to check for possible issues.

If you want to take advantage of the LSP and/or treesitter, you can install language
servers and parsers using the following command:

=:LspInstall (language)=
=:TSInstall (language)=

*NOTE:* If you want to use neorg's treesitter parser on macOS, you need to link GCC to CC. Instructions [[https://github.com/nvim-neorg/neorg/issues/74#issuecomment-906627223][here]].

I also recommend installing [[https://github.com/Kethku/neovide][Neovide]]

** Feedback
Suggestions/improvements
[[https://github.com/shaunsingh/vimrc-dotfiles/issues][welcome]]!
