# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = 
    { device = "/dev/disk/by-uuid/a2e98a1a-9138-43bb-a33a-c4fe89e0534f";
      fsType = "ext4";
    };

  fileSystems."/boot" = 
    { device = "/dev/disk/by-uuid/F868-D234";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGoverner = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
