#!/usr/bin/env sh

# managd
yabai -m config layout bsp

# Set all padding and gaps to 18pt (default: 0)
yabai -m config top_padding    18
yabai -m config bottom_padding 48
yabai -m config left_padding   18
yabai -m config right_padding  18
yabai -m config window_gap     18

# ignore apps
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Mail" manage=off
yabai -m rule --add app="Activity Monitor" manage=off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Scripting addon stuff
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
