#!/usr/bin/env sh

spacebar -m config position             bottom
spacebar -m config height               26
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        25
spacebar -m config text_font            "Liga SFMono Nerd Font:Medium:13.0"
spacebar -m config icon_font            "Liga SFMono Nerd Font:Light:13.0"
spacebar -m config background_color     0xff2E3440
spacebar -m config foreground_color     0xffD8DEE9
spacebar -m config space_icon_color     0xff8fBcBB
spacebar -m config power_icon_color     0xffEBCBDB
spacebar -m config battery_icon_color   0xffA3BE8C
spacebar -m config dnd_icon_color       0xffA3Be8C
spacebar -m config clock_icon_color     0xff81a1C1
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     I II III IV V VI VII VIII IX X
spacebar -m config space_icon           
spacebar -m config clock_icon           
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%d/%m/%y %R"
spacebar -m config right_shell          off

echo "spacebar configuration loaded.."
