name: "nix-config flake check"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.5.3
      with:
          fetch-depth: 0
    - uses: cachix/install-nix-action@v22
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.23.0pre20240603_da92ad7/install
        extra_nix_config: |
          experimental-features = ca-derivations nix-command flakes
    - run: nix flake check
